"""Add reservation_duration consttraint

Revision ID: 28373d21fbf5
Revises: 920d1a99131d
Create Date: 2025-04-10 15:50:17.116367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28373d21fbf5'
down_revision: Union[str, None] = '920d1a99131d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
